version: 1.0.{build}
skip_non_tags: true
image:
- Visual Studio 2017
- Visual Studio 2019
clone_folder: c:\lua-msvc
install:
  - appveyor DownloadFile https://github.com/Microsoft/vswhere/releases/download/2.3.2/vswhere.exe
  - appveyor DownloadFile https://www.lua.org/ftp/lua-$(APPVEYOR_REPO_TAG_NAME).tar.gz
  - tar zxvf lua-$(APPVEYOR_REPO_TAG_NAME).tar.gz
build_script:
- cmd: >-
    vsver.bat
    build.bat $(APPVEYOR_REPO_TAG_NAME) x86
    build.bat $(APPVEYOR_REPO_TAG_NAME) x64
artifacts:
  - path: build/lua-$(APPVEYOR_REPO_TAG_NAME)-vs$(VS_VERSION)-x86
    name: lua-$(APPVEYOR_REPO_TAG_NAME)-vs$(VS_VERSION)-x86
  - path: build/lua-$(APPVEYOR_REPO_TAG_NAME)-vs$(VS_VERSION)-x64
    name: lua-$(APPVEYOR_REPO_TAG_NAME)-vs$(VS_VERSION)-x64
deploy:
  release: Lua $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  force_update: true
  auth_token:
    secure: mqLDd9ouwepeyhnE8og1Q/bbB4NPcKI37t/vZN4ZFS6Sj4yT6KlHiBKAs+EmbNoR
  on:
    APPVEYOR_REPO_TAG: true
