version: 1.0.{build}
image:
- Visual Studio 2017
- Visual Studio 2019
clone_folder: c:\lua-msvc
build_script:
- cmd: >-
    appveyor DownloadFile https://github.com/Microsoft/vswhere/releases/download/2.3.2/vswhere.exe

    vsver.bat

    build.bat 5.3.5 x86

    build.bat 5.3.5 x64

artifacts:
  - path: build/lua-5.3.5-vs$(VS_VERSION)-x86
    name: lua-5.3.5-vs$(VS_VERSION)-x86
  - path: build/lua-5.3.5-vs$(VS_VERSION)-x64
    name: lua-5.3.5-vs$(VS_VERSION)-x64
deploy:
  release: Lua 5.3.5
  provider: GitHub
  artifact: build\*.zip
  draft: true
  auth_token:
    secure: mqLDd9ouwepeyhnE8og1Q/bbB4NPcKI37t/vZN4ZFS6Sj4yT6KlHiBKAs+EmbNoR
  #tag: $(APPVEYOR_REPO_TAG_NAME) # will not work until tag is pushed
  #on:
#   APPVEYOR_REPO_TAG: true   # deploy on tag push only
    #configuration: Release    # Debug contains non-redist MS DLLs
#   branch: master   # release from master branch only
